const skillCategories = new Map([
  // Amazon Skills
  ["Magic Arrow", "Bow and Crossbow Skills"],
  ["Fire Arrow", "Bow and Crossbow Skills"],
  ["Cold Arrow", "Bow and Crossbow Skills"],
  ["Multiple Shot", "Bow and Crossbow Skills"],
  ["Exploding Arrow", "Bow and Crossbow Skills"],
  ["Ice Arrow", "Bow and Crossbow Skills"],
  ["Guided Arrow", "Bow and Crossbow Skills"],
  ["Strafe", "Bow and Crossbow Skills"],
  ["Immolation Arrow", "Bow and Crossbow Skills"],
  ["Freezing Arrow", "Bow and Crossbow Skills"],

  ["Jab", "Javelin and Spear Skills"],
  ["Javelin and Spear Mastery", "Javelin and Spear Skills"],
  ["Power Strike", "Javelin and Spear Skills"],
  ["Poison Javelin", "Javelin and Spear Skills"],
  ["Impale", "Javelin and Spear Skills"],
  ["Lightning Strike", "Javelin and Spear Skills"],
  ["Charged Strike", "Javelin and Spear Skills"],
  ["Plague Javelin", "Javelin and Spear Skills"],
  ["Lightning Bolt", "Javelin and Spear Skills"],
  ["Lightning Fury", "Javelin and Spear Skills"],

  ["Inner Sight", "Passive and Magic Skills"],
  ["Critical Strike", "Passive and Magic Skills"],
  ["Dodge", "Passive and Magic Skills"],
  ["Slow Movement", "Passive and Magic Skills"],
  ["Avoid", "Passive and Magic Skills"],
  ["Penetrate", "Passive and Magic Skills"],
  ["Decoy", "Passive and Magic Skills"],
  ["Evade", "Passive and Magic Skills"],
  ["Valkyrie", "Passive and Magic Skills"],
  ["Pierce", "Passive and Magic Skills"],

  // Assassin Skills
  ["Fire Blast", "Martial Arts"],
  ["Shock Web", "Martial Arts"],
  ["Blade Sentinel", "Martial Arts"],
  ["Charged Bolt Sentry", "Martial Arts"],
  ["Wake of Fire", "Martial Arts"],
  ["Blade Fury", "Martial Arts"],
  ["Lightning Sentry", "Martial Arts"],
  ["Wake of Inferno", "Martial Arts"],
  ["Death Sentry", "Martial Arts"],
  ["Blade Shield", "Martial Arts"],

  ["Tiger Strike", "Shadow Disciplines"],
  ["Dragon Talon", "Shadow Disciplines"],
  ["Fists of Fire", "Shadow Disciplines"],
  ["Dragon Claw", "Shadow Disciplines"],
  ["Cobra Strike", "Shadow Disciplines"],
  ["Dragon Tail", "Shadow Disciplines"],
  ["Claws of Thunder", "Shadow Disciplines"],
  ["Dragon Flight", "Shadow Disciplines"],
  ["Blades of Ice", "Shadow Disciplines"],
  ["Phoenix Strike", "Shadow Disciplines"],

  ["Chain Lightning Sentry", "Traps"],
  ["Claw Mastery", "Traps"],
  ["Psychic Hammer", "Traps"],
  ["Burst of Speed", "Traps"],
  ["Weapon Block", "Traps"],
  ["Cloak of Shadows", "Traps"],
  ["Fade", "Traps"],
  ["Shadow Warrior", "Traps"],
  ["Mind Blast", "Traps"],
  ["Venom", "Traps"],
  ["Shadow Master", "Traps"],

  // Barbarian Skills
  ["Howl", "Warcries"],
  ["Find Potion", "Warcries"],
  ["Taunt", "Warcries"],
  ["Shout", "Warcries"],
  ["Find Item", "Warcries"],
  ["Battle Cry", "Warcries"],
  ["Battle Orders", "Warcries"],
  ["Grim Ward", "Warcries"],
  ["War Cry", "Warcries"],
  ["Battle Command", "Warcries"],

  ["Bash", "Combat Skills"],
  ["Leap", "Combat Skills"],
  ["Double Swing", "Combat Skills"],
  ["Stun", "Combat Skills"],
  ["Double Throw", "Combat Skills"],
  ["Leap Attack", "Combat Skills"],
  ["Concentrate", "Combat Skills"],
  ["Frenzy", "Combat Skills"],
  ["Whirlwind", "Combat Skills"],
  ["Berserk", "Combat Skills"],
  ["Battle Rage", "Combat Skills"],

  ["Sword Mastery", "Combat Masteries"],
  ["Pole Arm and Spear Mastery", "Combat Masteries"],
  ["Axe Mastery", "Combat Masteries"],
  ["Increased Speed", "Combat Masteries"],
  ["Mace Mastery", "Combat Masteries"],
  ["Pole Arm Mastery", "Combat Masteries"],
  ["Throwing Mastery", "Combat Masteries"],
  ["Spear Mastery", "Combat Masteries"],
  ["Combat Reflexes", "Combat Masteries"],
  ["Iron Skin", "Combat Masteries"],
  ["Deep Wounds", "Combat Masteries"],
  ["Natural Resistance", "Combat Masteries"],
  ["General Mastery", "Combat Masteries"],

  // Druid Skills
  ["Firestorm", "Elemental Skills"],
  ["Molten Boulder", "Elemental Skills"],
  ["Arctic Blast", "Elemental Skills"],
  ["Fissure", "Elemental Skills"],
  ["Cyclone Armor", "Elemental Skills"],
  ["Twister", "Elemental Skills"],
  ["Volcano", "Elemental Skills"],
  ["Tornado", "Elemental Skills"],
  ["Hurricane", "Elemental Skills"],
  ["Armageddon", "Elemental Skills"],
  ["Gust", "Elemental Skills"],

  ["Werewolf", "Shape Shifting Skills"],
  ["Lycanthropy", "Shape Shifting Skills"],
  ["Werebear", "Shape Shifting Skills"],
  ["Maul", "Shape Shifting Skills"],
  ["Feral Rage", "Shape Shifting Skills"],
  ["Fire Claws", "Shape Shifting Skills"],
  ["Rabies", "Shape Shifting Skills"],
  ["Shock Wave", "Shape Shifting Skills"],
  ["Hunger", "Shape Shifting Skills"],
  ["Fury", "Shape Shifting Skills"],

  ["Raven", "Summoning Skills"],
  ["Poison Creeper", "Summoning Skills"],
  ["Oak Sage", "Summoning Skills"],
  ["Summon Spirit Wolf", "Summoning Skills"],
  ["Carrion Vine", "Summoning Skills"],
  ["Heart of Wolverine", "Summoning Skills"],
  ["Summon Dire Wolf", "Summoning Skills"],
  ["Solar Creeper", "Summoning Skills"],
  ["Spirit of Barbs", "Summoning Skills"],
  ["Summon Grizzly", "Summoning Skills"],

  // Necromancer Skills
  ["Dark Pact", "Curses"],
  ["Amplify Damage", "Curses"],
  ["Dim Vision", "Curses"],
  ["Weaken", "Curses"],
  ["Iron Maiden", "Curses"],
  ["Terror", "Curses"],
  ["Confuse", "Curses"],
  ["Life Tap", "Curses"],
  ["Attract", "Curses"],
  ["Decrepify", "Curses"],
  ["Lower Resist", "Curses"],
  ["Curse Mastery", "Curses"],

  ["Raise Skeleton", "Summoning Spells"],
  ["Blood Warp", "Summoning Spells"],
  ["Skeleton Mastery", "Summoning Spells"],
  ["Clay Golem", "Summoning Spells"],
  ["Golem Mastery", "Summoning Spells"],
  ["Raise Skeletal Mage", "Summoning Spells"],
  ["Raise Skeleton Archer", "Summoning Spells"],
  ["Blood Golem", "Summoning Spells"],
  ["Iron Golem", "Summoning Spells"],
  ["Fire Golem", "Summoning Spells"],
  ["Revive", "Summoning Spells"],

  ["Teeth", "Poison and Bone Spells"],
  ["Bone Armor", "Poison and Bone Spells"],
  ["Poison Strike", "Poison and Bone Spells"],
  ["Corpse Explosion", "Poison and Bone Spells"],
  ["Desecrate", "Poison and Bone Spells"],
  ["Bone Wall", "Poison and Bone Spells"],
  ["Poison Nova", "Poison and Bone Spells"],
  ["Bone Spear", "Poison and Bone Spells"],
  ["Bone Spirit", "Poison and Bone Spells"],
  ["Bone Prison", "Poison and Bone Spells"],
  ["Bone Spikes", "Poison and Bone Spells"],

  // Paladin Skills
  ["Sacrifice", "Combat Skills"],
  ["Holy Nova", "Combat Skills"],
  ["Holy Light", "Combat Skills"],
  ["Joust", "Combat Skills"],
  ["Holy Sword", "Combat Skills"],
  ["Smite", "Combat Skills"],
  ["Holy Bolt", "Combat Skills"],
  ["Zeal", "Combat Skills"],
  ["Charge", "Combat Skills"],
  ["Vengeance", "Combat Skills"],
  ["Blessed Hammer", "Combat Skills"],
  ["Conversion", "Combat Skills"],
  ["Holy Shield", "Combat Skills"],
  ["Fist of the Heavens", "Combat Skills"],

  ["Might", "Offensive Auras"],
  ["Holy Fire", "Offensive Auras"],
  ["Thorns", "Offensive Auras"],
  ["Blessed Aim", "Offensive Auras"],
  ["Concentration", "Offensive Auras"],
  ["Holy Freeze", "Offensive Auras"],
  ["Holy Shock", "Offensive Auras"],
  ["Sanctuary", "Offensive Auras"],
  ["Fanaticism", "Offensive Auras"],
  ["Conviction", "Offensive Auras"],

  ["Prayer", "Defensive Auras"],
  ["Resist Fire", "Defensive Auras"],
  ["Defiance", "Defensive Auras"],
  ["Resist Cold", "Defensive Auras"],
  ["Cleansing", "Defensive Auras"],
  ["Resist Lightning", "Defensive Auras"],
  ["Vigor", "Defensive Auras"],
  ["Meditation", "Defensive Auras"],
  ["Redemption", "Defensive Auras"],
  ["Salvation", "Defensive Auras"],

  // Sorceress Skills
  ["Fire Bolt", "Fire Spells"],
  ["Warmth", "Fire Spells"],
  ["Inferno", "Fire Spells"],
  ["Blaze", "Fire Spells"],
  ["Fire Ball", "Fire Spells"],
  ["Fire Wall", "Fire Spells"],
  ["Enchant", "Fire Spells"],
  ["Meteor", "Fire Spells"],
  ["Fire Mastery", "Fire Spells"],
  ["Hydra", "Fire Spells"],
  ["Combustion", "Fire Spells"],
  ["Lesser Hydra", "Fire Spells"],

  ["Charged Bolt", "Lightning Spells"],
  ["Static Field", "Lightning Spells"],
  ["Telekinesis", "Lightning Spells"],
  ["Nova", "Lightning Spells"],
  ["Lightning", "Lightning Spells"],
  ["Chain Lightning", "Lightning Spells"],
  ["Teleport", "Lightning Spells"],
  ["Thunder Storm", "Lightning Spells"],
  ["Energy Shield", "Lightning Spells"],
  ["Lightning Mastery", "Lightning Spells"],

  ["Ice Bolt", "Cold Spells"],
  ["Ice Barrage", "Cold Spells"],
  ["Cold Enchant", "Cold Spells"],
  ["Frozen Armor", "Cold Spells"],
  ["Frost Nova", "Cold Spells"],
  ["Ice Blast", "Cold Spells"],
  ["Shiver Armor", "Cold Spells"],
  ["Glacial Spike", "Cold Spells"],
  ["Blizzard", "Cold Spells"],
  ["Chilling Armor", "Cold Spells"],
  ["Frozen Orb", "Cold Spells"],
  ["Cold Mastery", "Cold Spells"],
]);

export default skillCategories;
